name: reel_mood
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.0
  dio: ^5.4.0
  flutter_card_swiper: ^6.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  youtube_player_flutter: ^9.0.0
  url_launcher: ^6.3.0
  hydrated_bloc: ^9.1.0
  path_provider: ^2.1.4
  flutter_dotenv: ^6.0.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/icon/app_icon.png

  android_12:
    color: "#0F172A"
    image: assets/icon/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/app_icon.png
